spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: document-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/document/**

        - id: post-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/post/**